baseurl: https://ttscience.blog/
languageCode: en-US
title: TT Science dev blog
theme: "hugo-PaperMod"
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
permalinks:
  post: /:year/:month/:day/:slug/
services:
  googleAnalytics:
    id: "G-3MKP9QPBP1"
menu:
  main:
    - identifier: about
      name: About us
      url: /about/
      weight: 1
    - identifier: authors
      name: Authors
      url: /authors/
      weight: 2
    - identifier: archives
      name: Archive
      url: /archive/
      weight: 3
    - identifier: search
      name: Search
      url: /search/
      weight: 4
params:
  env: production
  math: true
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 3.2.2
  description: Development blog of Transition Technologies Science Clinical Data Science Team.
  defaultTheme: auto
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  homeInfoParams:
    Title: "Hey there, data enthusiasts! 👋"
    Content: "You can browse our latest entries below or use the menu above to explore archives, learn more about us, or get in touch. The layout insists on being thorough, so we’re rolling with it!"
  assets:
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
  socialIcons:
    - name: "Company website"
      url: "https://ttsi.com.pl/"
    - name: "GitHub"
      url: "https://github.com/ttscience"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/company/transition-technologies-science-sp-z-o-o/"
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
  ShowShareButtons: true
markup:
  highlight:
    noClasses: false # Use classes for more customizable styling via CSS
    style: "github" # Choose a Chroma theme you like (e.g., "monokai", "dracula", "github")
    codeFences: true # Enable syntax highlighting for code fences
    guessSyntax: true # Automatically guess the language if not specified
  goldmark:
    renderer:
      unsafe: true
outputs:
  home:
    - HTML
    - RSS
    - JSON
